/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelos;

import java.util.Calendar;

/**
 *
 * @author Jean
 */
public class RelatorioPrincipal {

    private int RELATORIO_ID;
    private String RELATORIO_AREA_UTIL;
    private String RELATORIO_AREA_COBERTA;
    private String RELATORIO_AREA_DESCOBERTA;
    private String RELATORIO_N_HABITACOES;
    private String RELATORIO_AREA_INTERVENCAO;
    private String RELATORIO_ALTURA_DO_TALUDE;
    private int CLIENTE_ID;
    private int RELATORIO_TIPO_DE_FINANCIAMENTO;
    private int RELATORIO_LOCALIZACAO;
    private int RELATORIO_INSERIDO_EM_AREA;
    private String RELATORIO_INSERIDO_EM_AREA_OUTRA_ESPECIFICAR;
    private String RELATORIO_LOCALIZACAO_LEI;
    private String RELATORIO_LOCALIZACAO_PLANO;
    private int RELATORIO_HA_RESIDENCIAS;
    private int RELATORIO_AREA_DA_UC;
    private String RELATORIO_AREA_DA_UC_NOME;
    private String RELATORIO_AREA_DA_UC_ADMINISTRADOR;
    private String RELATORIO_AREA_DA_UC_N_DOCUMENTO;
    private int RELATORIO_HA_PATRIMONIO;
    private String RELATORIO_N_IPHAN;
    private int RELATORIO_SUPRECAO_VEGETACAO;
    private String RELATORIO_SUPRECAO_VEGETACAO_DOCUMENTO_IDAF;
    private String RELATORIO_LOTE_DE_MENOR_AREA;
    private int RELATORIO_CONDICOES_DO_TERRENO;
    private int RELATORIO_CONDICOES_DO_TERRENO_OPCOES;
    private String RELATORIO_CONDICOES_DO_TERRENO_ESPECIFICAR;
    private int RELATORIO_DECLIVIDADE;
    private String RELATORIO_DECLIVIDADE_ESPECIFICAR;
    private String RELATORIO_COORDENADAS_UTM_N;
    private String RELATORIO_COORDENADAS_UTM_E;
    private int RELATORIO_INFORMACOES_SOBRE_A_ATIVIDADE;
    private Calendar RELATORIO_I_S_A_DATA;
    private String RELATORIO_I_S_A_PREVISAO_OPERACAO;
    private String RELATORIO_I_S_A_N_EMPREGADOS;
    private String RELATORIO_I_S_A_AREA_TOTAL_MOVIMENTACAO_TERRA;
    private String RELATORIO_I_S_A_AREA_DE_CORTE;
    private String RELATORIO_I_S_A_AREA_DE_ATERRO;
    private String RELATORIO_I_S_A_TALUDES_FORMADOS;
    private int RELATORIO_SISTEMA_DE_DRENAGEM_PLUVIAL_EXISTENTE;
    private String RELATORIO_S_D_P_E_ESPECIFICAR;
    private int RELATORIO_RECURSOS_HIDRICOS_1;
    private String RELATORIO_R_H_NOME_1;
    private String RELATORIO_R_H_DISTANCIA_1;
    private int RELATORIO_BOTA_FORA1;
    private String RELATORIO_BOTA_FORA_UTM_N1;
    private String RELATORIO_BOTA_FORA_UTM_E1;
    private int RELATORIO_BOTA_FORA_OPCAO_1;
    private int RELATORIO_BOTA_FORA_OPCAO_2;
    private String RELATORIO_BOTA_FORA_N_DA_UC1;
    private int RELATORIO_BOTA_FORA2;
    private String RELATORIO_BOTA_FORA_UTM_N2;
    private String RELATORIO_BOTA_FORA_UTM_E2;
    private String RELATORIO_BOTA_FORA_AREA_EMPRESTIMO;
    private int RELATORIO_BOTA_FORA_OPCAO_3;
    private int RELATORIO_BOTA_FORA_OPCAO_4;
    private String RELATORIO_BOTA_FORA_N_DA_UC2;
    private int RELATORIO_RECURSOS_HIDRICOS_2;
    private String RELATORIO_R_H_NOME_2;
    private String RELATORIO_R_H_DISTANCIA_2;
    private int RELATORIO_COMPLEMENTACAO_DO_SERVICO_TERRAPLANAGEM;
    private String RELATORIO_C_S_T_UTM_N;
    private String RELATORIO_C_S_T_UTM_E;
    private String RELATORIO_C_S_T_AREA_EMPRESTIMO;
    private int RELATORIO_C_S_T_OPCAO_1;
    private int RELATORIO_C_S_T_OPCAO_2;
    private String RELATORIO_C_S_T_N_DA_UC;
    private int RELATORIO_RECURSOS_HIDRICOS_3;
    private String RELATORIO_R_H_NOME_3;
    private String RELATORIO_R_H_DISTANCIA_3;
    private String RELATORIO_FONTES_DE_ABASTECIMENTO_AGUA;
    private String RELATORIO_F_A_A_EMPRESA;
    private String RELATORIO_F_A_A_POCO_TIPO;
    private String RELATORIO_F_A_A_POCO_QTD;
    private String RELATORIO_F_A_A_NUMERO_LICENCA;
    private String RELATORIO_F_A_A_CURSO_DAGUA_NOME;
    private String RELATORIO_F_A_A_LAGO_NOME;
    private String RELATORIO_F_A_A_AGUAS_COSTEIRAS_ESPECIFICAR;
    private String RELATORIO_F_A_A_OUTRAS_ESPECIFICAR;
    private String RELATORIO_F_A_A_CONSUMO_DE_AGUA;
    private String RELATORIO_F_A_A_N_DOCUMENTO_OUTORGA_R_H;
    private String RELATORIO_F_A_A_N_DOCUMENTO_CERTIDAO_D_O;
    private String RELATORIO_FONTES_DE_GERACAO_EFLUENTES;
    private int RELATORIO_MOVIMENTACAO_DE_TERRA;
    private String RELATORIO_F_G_E_OUTRO_ESPECIFICAR_1;
    private String RELATORIO_F_G_E_OUTRO_ESPECIFICAR_2;
    private String RELATORIO_MANUTENCAO_DO_SISTEMA_DE_TRATAMENTO;
    private String RELATORIO_M_S_T_ESPECIFICAR;
    private String RELATORIO_M_S_T_CAIXA_DE_GORDURA;
    private String RELATORIO_M_S_T_CAIXA_DE_GORDURA_ESPECIFICAR;
    private String RELATORIO_GERENCIAMENTO_DE_RESIDUOS;
    private String RELATORIO_G_R_ESPECIFICAR_1;
    private String RELATORIO_G_R_ESPECIFICAR_2;
    private String RELATORIO_G_R_ESPECIFICAR_3;
    private String RELATORIO_G_R_NOME_1;
    private String RELATORIO_G_R_NOME_2;
    private String RELATORIO_G_R_NOME_3;
    private String RELATORIO_G_R_NUMERO_LICENCA_1;
    private String RELATORIO_G_R_NUMERO_LICENCA_2;
    private String RELATORIO_G_R_NUMERO_LICENCA_3;
    private String RELATORIO_G_R_CONSUMEO_DE_AGUA_L_DIA;
    private String RELATORIO_G_R_CONSUMEO_DE_AGUA_M_MES;
    private String RELATORIO_EMISSOES_ATMOSFERICAS;
    private String RELATORIO_E_A_ESPECIFICAR;
    private String RELATORIO_ROTEIRO_DE_ACESSO;
    private String RELATORIO_CROQUI_DE_LOCALIZACAO_EMPREENDIMENTO;
    private int RELATORIO_CROQUI_PERGUNTA;
    private String RELATORIO_TEXTO_ANEXO;
    private Calendar RELATORIO_DATA_ATUAL;
    private int PROFISSIONAL_ID;
    private int CATEGORIA_ID;
    private String CLIENTE_NOME;
    private String CLIENTE_FANTASIA;
    private String CLIENTE_ENDERECO;
    private String CLIENTE_MUNICIPIO;
    private String CLIENTE_NUMERO;
    private String CLIENTE_BAIRRO;
    private String CLIENTE_TELEFONE;
    private String CLIENTE_CELULAR;
    private String CLIENTE_CEP;
    private String CLIENTE_CPF;
    private String CLIENTE_CNPJ;
    private String CLIENTE_UTMN;
    private String CLIENTE_UTME;
    private Calendar CLIENTE_DATA;
    private String PROFISSIONAL_NOME;
    private String CATEGORIA_NOME;
    private int REPRESENTANTE_ID;
    private String REPRESENTANTE_NOME;

    public int getRELATORIO_ID() {
        return RELATORIO_ID;
    }

    public void setRELATORIO_ID(int RELATORIO_ID) {
        this.RELATORIO_ID = RELATORIO_ID;
    }

    public String getRELATORIO_AREA_UTIL() {
        return RELATORIO_AREA_UTIL;
    }

    public void setRELATORIO_AREA_UTIL(String RELATORIO_AREA_UTIL) {
        this.RELATORIO_AREA_UTIL = RELATORIO_AREA_UTIL;
    }

    public String getRELATORIO_AREA_COBERTA() {
        return RELATORIO_AREA_COBERTA;
    }

    public void setRELATORIO_AREA_COBERTA(String RELATORIO_AREA_COBERTA) {
        this.RELATORIO_AREA_COBERTA = RELATORIO_AREA_COBERTA;
    }

    public String getRELATORIO_AREA_DESCOBERTA() {
        return RELATORIO_AREA_DESCOBERTA;
    }

    public void setRELATORIO_AREA_DESCOBERTA(String RELATORIO_AREA_DESCOBERTA) {
        this.RELATORIO_AREA_DESCOBERTA = RELATORIO_AREA_DESCOBERTA;
    }

    public String getRELATORIO_N_HABITACOES() {
        return RELATORIO_N_HABITACOES;
    }

    public void setRELATORIO_N_HABITACOES(String RELATORIO_N_HABITACOES) {
        this.RELATORIO_N_HABITACOES = RELATORIO_N_HABITACOES;
    }

    public String getRELATORIO_AREA_INTERVENCAO() {
        return RELATORIO_AREA_INTERVENCAO;
    }

    public void setRELATORIO_AREA_INTERVENCAO(String RELATORIO_AREA_INTERVENCAO) {
        this.RELATORIO_AREA_INTERVENCAO = RELATORIO_AREA_INTERVENCAO;
    }

    public String getRELATORIO_ALTURA_DO_TALUDE() {
        return RELATORIO_ALTURA_DO_TALUDE;
    }

    public void setRELATORIO_ALTURA_DO_TALUDE(String RELATORIO_ALTURA_DO_TALUDE) {
        this.RELATORIO_ALTURA_DO_TALUDE = RELATORIO_ALTURA_DO_TALUDE;
    }

    public int getCLIENTE_ID() {
        return CLIENTE_ID;
    }

    public void setCLIENTE_ID(int CLIENTE_ID) {
        this.CLIENTE_ID = CLIENTE_ID;
    }

    public int getRELATORIO_TIPO_DE_FINANCIAMENTO() {
        return RELATORIO_TIPO_DE_FINANCIAMENTO;
    }

    public void setRELATORIO_TIPO_DE_FINANCIAMENTO(int RELATORIO_TIPO_DE_FINANCIAMENTO) {
        this.RELATORIO_TIPO_DE_FINANCIAMENTO = RELATORIO_TIPO_DE_FINANCIAMENTO;
    }

    public int getRELATORIO_LOCALIZACAO() {
        return RELATORIO_LOCALIZACAO;
    }

    public void setRELATORIO_LOCALIZACAO(int RELATORIO_LOCALIZACAO) {
        this.RELATORIO_LOCALIZACAO = RELATORIO_LOCALIZACAO;
    }

    public int getRELATORIO_INSERIDO_EM_AREA() {
        return RELATORIO_INSERIDO_EM_AREA;
    }

    public void setRELATORIO_INSERIDO_EM_AREA(int RELATORIO_INSERIDO_EM_AREA) {
        this.RELATORIO_INSERIDO_EM_AREA = RELATORIO_INSERIDO_EM_AREA;
    }

    public String getRELATORIO_INSERIDO_EM_AREA_OUTRA_ESPECIFICAR() {
        return RELATORIO_INSERIDO_EM_AREA_OUTRA_ESPECIFICAR;
    }

    public void setRELATORIO_INSERIDO_EM_AREA_OUTRA_ESPECIFICAR(String RELATORIO_INSERIDO_EM_AREA_OUTRA_ESPECIFICAR) {
        this.RELATORIO_INSERIDO_EM_AREA_OUTRA_ESPECIFICAR = RELATORIO_INSERIDO_EM_AREA_OUTRA_ESPECIFICAR;
    }

    public String getRELATORIO_LOCALIZACAO_LEI() {
        return RELATORIO_LOCALIZACAO_LEI;
    }

    public void setRELATORIO_LOCALIZACAO_LEI(String RELATORIO_LOCALIZACAO_LEI) {
        this.RELATORIO_LOCALIZACAO_LEI = RELATORIO_LOCALIZACAO_LEI;
    }

    public String getRELATORIO_LOCALIZACAO_PLANO() {
        return RELATORIO_LOCALIZACAO_PLANO;
    }

    public void setRELATORIO_LOCALIZACAO_PLANO(String RELATORIO_LOCALIZACAO_PLANO) {
        this.RELATORIO_LOCALIZACAO_PLANO = RELATORIO_LOCALIZACAO_PLANO;
    }

    public int getRELATORIO_HA_RESIDENCIAS() {
        return RELATORIO_HA_RESIDENCIAS;
    }

    public void setRELATORIO_HA_RESIDENCIAS(int RELATORIO_HA_RESIDENCIAS) {
        this.RELATORIO_HA_RESIDENCIAS = RELATORIO_HA_RESIDENCIAS;
    }

    public int getRELATORIO_AREA_DA_UC() {
        return RELATORIO_AREA_DA_UC;
    }

    public void setRELATORIO_AREA_DA_UC(int RELATORIO_AREA_DA_UC) {
        this.RELATORIO_AREA_DA_UC = RELATORIO_AREA_DA_UC;
    }

    public String getRELATORIO_AREA_DA_UC_NOME() {
        return RELATORIO_AREA_DA_UC_NOME;
    }

    public void setRELATORIO_AREA_DA_UC_NOME(String RELATORIO_AREA_DA_UC_NOME) {
        this.RELATORIO_AREA_DA_UC_NOME = RELATORIO_AREA_DA_UC_NOME;
    }

    public String getRELATORIO_AREA_DA_UC_ADMINISTRADOR() {
        return RELATORIO_AREA_DA_UC_ADMINISTRADOR;
    }

    public void setRELATORIO_AREA_DA_UC_ADMINISTRADOR(String RELATORIO_AREA_DA_UC_ADMINISTRADOR) {
        this.RELATORIO_AREA_DA_UC_ADMINISTRADOR = RELATORIO_AREA_DA_UC_ADMINISTRADOR;
    }

    public String getRELATORIO_AREA_DA_UC_N_DOCUMENTO() {
        return RELATORIO_AREA_DA_UC_N_DOCUMENTO;
    }

    public void setRELATORIO_AREA_DA_UC_N_DOCUMENTO(String RELATORIO_AREA_DA_UC_N_DOCUMENTO) {
        this.RELATORIO_AREA_DA_UC_N_DOCUMENTO = RELATORIO_AREA_DA_UC_N_DOCUMENTO;
    }

    public int getRELATORIO_HA_PATRIMONIO() {
        return RELATORIO_HA_PATRIMONIO;
    }

    public void setRELATORIO_HA_PATRIMONIO(int RELATORIO_HA_PATRIMONIO) {
        this.RELATORIO_HA_PATRIMONIO = RELATORIO_HA_PATRIMONIO;
    }

    public String getRELATORIO_N_IPHAN() {
        return RELATORIO_N_IPHAN;
    }

    public void setRELATORIO_N_IPHAN(String RELATORIO_N_IPHAN) {
        this.RELATORIO_N_IPHAN = RELATORIO_N_IPHAN;
    }

    public int getRELATORIO_SUPRECAO_VEGETACAO() {
        return RELATORIO_SUPRECAO_VEGETACAO;
    }

    public void setRELATORIO_SUPRECAO_VEGETACAO(int RELATORIO_SUPRECAO_VEGETACAO) {
        this.RELATORIO_SUPRECAO_VEGETACAO = RELATORIO_SUPRECAO_VEGETACAO;
    }

    public String getRELATORIO_SUPRECAO_VEGETACAO_DOCUMENTO_IDAF() {
        return RELATORIO_SUPRECAO_VEGETACAO_DOCUMENTO_IDAF;
    }

    public void setRELATORIO_SUPRECAO_VEGETACAO_DOCUMENTO_IDAF(String RELATORIO_SUPRECAO_VEGETACAO_DOCUMENTO_IDAF) {
        this.RELATORIO_SUPRECAO_VEGETACAO_DOCUMENTO_IDAF = RELATORIO_SUPRECAO_VEGETACAO_DOCUMENTO_IDAF;
    }

    public String getRELATORIO_LOTE_DE_MENOR_AREA() {
        return RELATORIO_LOTE_DE_MENOR_AREA;
    }

    public void setRELATORIO_LOTE_DE_MENOR_AREA(String RELATORIO_LOTE_DE_MENOR_AREA) {
        this.RELATORIO_LOTE_DE_MENOR_AREA = RELATORIO_LOTE_DE_MENOR_AREA;
    }

    public int getRELATORIO_CONDICOES_DO_TERRENO() {
        return RELATORIO_CONDICOES_DO_TERRENO;
    }

    public void setRELATORIO_CONDICOES_DO_TERRENO(int RELATORIO_CONDICOES_DO_TERRENO) {
        this.RELATORIO_CONDICOES_DO_TERRENO = RELATORIO_CONDICOES_DO_TERRENO;
    }

    public int getRELATORIO_CONDICOES_DO_TERRENO_OPCOES() {
        return RELATORIO_CONDICOES_DO_TERRENO_OPCOES;
    }

    public void setRELATORIO_CONDICOES_DO_TERRENO_OPCOES(int RELATORIO_CONDICOES_DO_TERRENO_OPCOES) {
        this.RELATORIO_CONDICOES_DO_TERRENO_OPCOES = RELATORIO_CONDICOES_DO_TERRENO_OPCOES;
    }

    public String getRELATORIO_CONDICOES_DO_TERRENO_ESPECIFICAR() {
        return RELATORIO_CONDICOES_DO_TERRENO_ESPECIFICAR;
    }

    public void setRELATORIO_CONDICOES_DO_TERRENO_ESPECIFICAR(String RELATORIO_CONDICOES_DO_TERRENO_ESPECIFICAR) {
        this.RELATORIO_CONDICOES_DO_TERRENO_ESPECIFICAR = RELATORIO_CONDICOES_DO_TERRENO_ESPECIFICAR;
    }

    public int getRELATORIO_DECLIVIDADE() {
        return RELATORIO_DECLIVIDADE;
    }

    public void setRELATORIO_DECLIVIDADE(int RELATORIO_DECLIVIDADE) {
        this.RELATORIO_DECLIVIDADE = RELATORIO_DECLIVIDADE;
    }

    public String getRELATORIO_DECLIVIDADE_ESPECIFICAR() {
        return RELATORIO_DECLIVIDADE_ESPECIFICAR;
    }

    public void setRELATORIO_DECLIVIDADE_ESPECIFICAR(String RELATORIO_DECLIVIDADE_ESPECIFICAR) {
        this.RELATORIO_DECLIVIDADE_ESPECIFICAR = RELATORIO_DECLIVIDADE_ESPECIFICAR;
    }

    public String getRELATORIO_COORDENADAS_UTM_N() {
        return RELATORIO_COORDENADAS_UTM_N;
    }

    public void setRELATORIO_COORDENADAS_UTM_N(String RELATORIO_COORDENADAS_UTM_N) {
        this.RELATORIO_COORDENADAS_UTM_N = RELATORIO_COORDENADAS_UTM_N;
    }

    public String getRELATORIO_COORDENADAS_UTM_E() {
        return RELATORIO_COORDENADAS_UTM_E;
    }

    public void setRELATORIO_COORDENADAS_UTM_E(String RELATORIO_COORDENADAS_UTM_E) {
        this.RELATORIO_COORDENADAS_UTM_E = RELATORIO_COORDENADAS_UTM_E;
    }

    public int getRELATORIO_INFORMACOES_SOBRE_A_ATIVIDADE() {
        return RELATORIO_INFORMACOES_SOBRE_A_ATIVIDADE;
    }

    public void setRELATORIO_INFORMACOES_SOBRE_A_ATIVIDADE(int RELATORIO_INFORMACOES_SOBRE_A_ATIVIDADE) {
        this.RELATORIO_INFORMACOES_SOBRE_A_ATIVIDADE = RELATORIO_INFORMACOES_SOBRE_A_ATIVIDADE;
    }

    public Calendar getRELATORIO_I_S_A_DATA() {
        return RELATORIO_I_S_A_DATA;
    }

    public void setRELATORIO_I_S_A_DATA(Calendar RELATORIO_I_S_A_DATA) {
        this.RELATORIO_I_S_A_DATA = RELATORIO_I_S_A_DATA;
    }

    public String getRELATORIO_I_S_A_PREVISAO_OPERACAO() {
        return RELATORIO_I_S_A_PREVISAO_OPERACAO;
    }

    public void setRELATORIO_I_S_A_PREVISAO_OPERACAO(String RELATORIO_I_S_A_PREVISAO_OPERACAO) {
        this.RELATORIO_I_S_A_PREVISAO_OPERACAO = RELATORIO_I_S_A_PREVISAO_OPERACAO;
    }

    public String getRELATORIO_I_S_A_N_EMPREGADOS() {
        return RELATORIO_I_S_A_N_EMPREGADOS;
    }

    public void setRELATORIO_I_S_A_N_EMPREGADOS(String RELATORIO_I_S_A_N_EMPREGADOS) {
        this.RELATORIO_I_S_A_N_EMPREGADOS = RELATORIO_I_S_A_N_EMPREGADOS;
    }

    public String getRELATORIO_I_S_A_AREA_TOTAL_MOVIMENTACAO_TERRA() {
        return RELATORIO_I_S_A_AREA_TOTAL_MOVIMENTACAO_TERRA;
    }

    public void setRELATORIO_I_S_A_AREA_TOTAL_MOVIMENTACAO_TERRA(String RELATORIO_I_S_A_AREA_TOTAL_MOVIMENTACAO_TERRA) {
        this.RELATORIO_I_S_A_AREA_TOTAL_MOVIMENTACAO_TERRA = RELATORIO_I_S_A_AREA_TOTAL_MOVIMENTACAO_TERRA;
    }

    public String getRELATORIO_I_S_A_AREA_DE_CORTE() {
        return RELATORIO_I_S_A_AREA_DE_CORTE;
    }

    public void setRELATORIO_I_S_A_AREA_DE_CORTE(String RELATORIO_I_S_A_AREA_DE_CORTE) {
        this.RELATORIO_I_S_A_AREA_DE_CORTE = RELATORIO_I_S_A_AREA_DE_CORTE;
    }

    public String getRELATORIO_I_S_A_AREA_DE_ATERRO() {
        return RELATORIO_I_S_A_AREA_DE_ATERRO;
    }

    public void setRELATORIO_I_S_A_AREA_DE_ATERRO(String RELATORIO_I_S_A_AREA_DE_ATERRO) {
        this.RELATORIO_I_S_A_AREA_DE_ATERRO = RELATORIO_I_S_A_AREA_DE_ATERRO;
    }

    public String getRELATORIO_I_S_A_TALUDES_FORMADOS() {
        return RELATORIO_I_S_A_TALUDES_FORMADOS;
    }

    public void setRELATORIO_I_S_A_TALUDES_FORMADOS(String RELATORIO_I_S_A_TALUDES_FORMADOS) {
        this.RELATORIO_I_S_A_TALUDES_FORMADOS = RELATORIO_I_S_A_TALUDES_FORMADOS;
    }

    public int getRELATORIO_SISTEMA_DE_DRENAGEM_PLUVIAL_EXISTENTE() {
        return RELATORIO_SISTEMA_DE_DRENAGEM_PLUVIAL_EXISTENTE;
    }

    public void setRELATORIO_SISTEMA_DE_DRENAGEM_PLUVIAL_EXISTENTE(int RELATORIO_SISTEMA_DE_DRENAGEM_PLUVIAL_EXISTENTE) {
        this.RELATORIO_SISTEMA_DE_DRENAGEM_PLUVIAL_EXISTENTE = RELATORIO_SISTEMA_DE_DRENAGEM_PLUVIAL_EXISTENTE;
    }

    public String getRELATORIO_S_D_P_E_ESPECIFICAR() {
        return RELATORIO_S_D_P_E_ESPECIFICAR;
    }

    public void setRELATORIO_S_D_P_E_ESPECIFICAR(String RELATORIO_S_D_P_E_ESPECIFICAR) {
        this.RELATORIO_S_D_P_E_ESPECIFICAR = RELATORIO_S_D_P_E_ESPECIFICAR;
    }

    public int getRELATORIO_RECURSOS_HIDRICOS_1() {
        return RELATORIO_RECURSOS_HIDRICOS_1;
    }

    public void setRELATORIO_RECURSOS_HIDRICOS_1(int RELATORIO_RECURSOS_HIDRICOS_1) {
        this.RELATORIO_RECURSOS_HIDRICOS_1 = RELATORIO_RECURSOS_HIDRICOS_1;
    }

    public String getRELATORIO_R_H_NOME_1() {
        return RELATORIO_R_H_NOME_1;
    }

    public void setRELATORIO_R_H_NOME_1(String RELATORIO_R_H_NOME_1) {
        this.RELATORIO_R_H_NOME_1 = RELATORIO_R_H_NOME_1;
    }

    public String getRELATORIO_R_H_DISTANCIA_1() {
        return RELATORIO_R_H_DISTANCIA_1;
    }

    public void setRELATORIO_R_H_DISTANCIA_1(String RELATORIO_R_H_DISTANCIA_1) {
        this.RELATORIO_R_H_DISTANCIA_1 = RELATORIO_R_H_DISTANCIA_1;
    }

    public int getRELATORIO_BOTA_FORA1() {
        return RELATORIO_BOTA_FORA1;
    }

    public void setRELATORIO_BOTA_FORA1(int RELATORIO_BOTA_FORA1) {
        this.RELATORIO_BOTA_FORA1 = RELATORIO_BOTA_FORA1;
    }

    public String getRELATORIO_BOTA_FORA_UTM_N1() {
        return RELATORIO_BOTA_FORA_UTM_N1;
    }

    public void setRELATORIO_BOTA_FORA_UTM_N1(String RELATORIO_BOTA_FORA_UTM_N1) {
        this.RELATORIO_BOTA_FORA_UTM_N1 = RELATORIO_BOTA_FORA_UTM_N1;
    }

    public String getRELATORIO_BOTA_FORA_UTM_E1() {
        return RELATORIO_BOTA_FORA_UTM_E1;
    }

    public void setRELATORIO_BOTA_FORA_UTM_E1(String RELATORIO_BOTA_FORA_UTM_E1) {
        this.RELATORIO_BOTA_FORA_UTM_E1 = RELATORIO_BOTA_FORA_UTM_E1;
    }

    public int getRELATORIO_BOTA_FORA_OPCAO_1() {
        return RELATORIO_BOTA_FORA_OPCAO_1;
    }

    public void setRELATORIO_BOTA_FORA_OPCAO_1(int RELATORIO_BOTA_FORA_OPCAO_1) {
        this.RELATORIO_BOTA_FORA_OPCAO_1 = RELATORIO_BOTA_FORA_OPCAO_1;
    }

    public int getRELATORIO_BOTA_FORA_OPCAO_2() {
        return RELATORIO_BOTA_FORA_OPCAO_2;
    }

    public void setRELATORIO_BOTA_FORA_OPCAO_2(int RELATORIO_BOTA_FORA_OPCAO_2) {
        this.RELATORIO_BOTA_FORA_OPCAO_2 = RELATORIO_BOTA_FORA_OPCAO_2;
    }

    public String getRELATORIO_BOTA_FORA_N_DA_UC1() {
        return RELATORIO_BOTA_FORA_N_DA_UC1;
    }

    public void setRELATORIO_BOTA_FORA_N_DA_UC1(String RELATORIO_BOTA_FORA_N_DA_UC1) {
        this.RELATORIO_BOTA_FORA_N_DA_UC1 = RELATORIO_BOTA_FORA_N_DA_UC1;
    }

    public int getRELATORIO_BOTA_FORA2() {
        return RELATORIO_BOTA_FORA2;
    }

    public void setRELATORIO_BOTA_FORA2(int RELATORIO_BOTA_FORA2) {
        this.RELATORIO_BOTA_FORA2 = RELATORIO_BOTA_FORA2;
    }

    public String getRELATORIO_BOTA_FORA_UTM_N2() {
        return RELATORIO_BOTA_FORA_UTM_N2;
    }

    public void setRELATORIO_BOTA_FORA_UTM_N2(String RELATORIO_BOTA_FORA_UTM_N2) {
        this.RELATORIO_BOTA_FORA_UTM_N2 = RELATORIO_BOTA_FORA_UTM_N2;
    }

    public String getRELATORIO_BOTA_FORA_UTM_E2() {
        return RELATORIO_BOTA_FORA_UTM_E2;
    }

    public void setRELATORIO_BOTA_FORA_UTM_E2(String RELATORIO_BOTA_FORA_UTM_E2) {
        this.RELATORIO_BOTA_FORA_UTM_E2 = RELATORIO_BOTA_FORA_UTM_E2;
    }

    public String getRELATORIO_BOTA_FORA_AREA_EMPRESTIMO() {
        return RELATORIO_BOTA_FORA_AREA_EMPRESTIMO;
    }

    public void setRELATORIO_BOTA_FORA_AREA_EMPRESTIMO(String RELATORIO_BOTA_FORA_AREA_EMPRESTIMO) {
        this.RELATORIO_BOTA_FORA_AREA_EMPRESTIMO = RELATORIO_BOTA_FORA_AREA_EMPRESTIMO;
    }

    public int getRELATORIO_BOTA_FORA_OPCAO_3() {
        return RELATORIO_BOTA_FORA_OPCAO_3;
    }

    public void setRELATORIO_BOTA_FORA_OPCAO_3(int RELATORIO_BOTA_FORA_OPCAO_3) {
        this.RELATORIO_BOTA_FORA_OPCAO_3 = RELATORIO_BOTA_FORA_OPCAO_3;
    }

    public int getRELATORIO_BOTA_FORA_OPCAO_4() {
        return RELATORIO_BOTA_FORA_OPCAO_4;
    }

    public void setRELATORIO_BOTA_FORA_OPCAO_4(int RELATORIO_BOTA_FORA_OPCAO_4) {
        this.RELATORIO_BOTA_FORA_OPCAO_4 = RELATORIO_BOTA_FORA_OPCAO_4;
    }

    public String getRELATORIO_BOTA_FORA_N_DA_UC2() {
        return RELATORIO_BOTA_FORA_N_DA_UC2;
    }

    public void setRELATORIO_BOTA_FORA_N_DA_UC2(String RELATORIO_BOTA_FORA_N_DA_UC2) {
        this.RELATORIO_BOTA_FORA_N_DA_UC2 = RELATORIO_BOTA_FORA_N_DA_UC2;
    }

    public int getRELATORIO_RECURSOS_HIDRICOS_2() {
        return RELATORIO_RECURSOS_HIDRICOS_2;
    }

    public void setRELATORIO_RECURSOS_HIDRICOS_2(int RELATORIO_RECURSOS_HIDRICOS_2) {
        this.RELATORIO_RECURSOS_HIDRICOS_2 = RELATORIO_RECURSOS_HIDRICOS_2;
    }

    public String getRELATORIO_R_H_NOME_2() {
        return RELATORIO_R_H_NOME_2;
    }

    public void setRELATORIO_R_H_NOME_2(String RELATORIO_R_H_NOME_2) {
        this.RELATORIO_R_H_NOME_2 = RELATORIO_R_H_NOME_2;
    }

    public String getRELATORIO_R_H_DISTANCIA_2() {
        return RELATORIO_R_H_DISTANCIA_2;
    }

    public void setRELATORIO_R_H_DISTANCIA_2(String RELATORIO_R_H_DISTANCIA_2) {
        this.RELATORIO_R_H_DISTANCIA_2 = RELATORIO_R_H_DISTANCIA_2;
    }

    public int getRELATORIO_COMPLEMENTACAO_DO_SERVICO_TERRAPLANAGEM() {
        return RELATORIO_COMPLEMENTACAO_DO_SERVICO_TERRAPLANAGEM;
    }

    public void setRELATORIO_COMPLEMENTACAO_DO_SERVICO_TERRAPLANAGEM(int RELATORIO_COMPLEMENTACAO_DO_SERVICO_TERRAPLANAGEM) {
        this.RELATORIO_COMPLEMENTACAO_DO_SERVICO_TERRAPLANAGEM = RELATORIO_COMPLEMENTACAO_DO_SERVICO_TERRAPLANAGEM;
    }

    public String getRELATORIO_C_S_T_UTM_N() {
        return RELATORIO_C_S_T_UTM_N;
    }

    public void setRELATORIO_C_S_T_UTM_N(String RELATORIO_C_S_T_UTM_N) {
        this.RELATORIO_C_S_T_UTM_N = RELATORIO_C_S_T_UTM_N;
    }

    public String getRELATORIO_C_S_T_UTM_E() {
        return RELATORIO_C_S_T_UTM_E;
    }

    public void setRELATORIO_C_S_T_UTM_E(String RELATORIO_C_S_T_UTM_E) {
        this.RELATORIO_C_S_T_UTM_E = RELATORIO_C_S_T_UTM_E;
    }

    public String getRELATORIO_C_S_T_AREA_EMPRESTIMO() {
        return RELATORIO_C_S_T_AREA_EMPRESTIMO;
    }

    public void setRELATORIO_C_S_T_AREA_EMPRESTIMO(String RELATORIO_C_S_T_AREA_EMPRESTIMO) {
        this.RELATORIO_C_S_T_AREA_EMPRESTIMO = RELATORIO_C_S_T_AREA_EMPRESTIMO;
    }

    public int getRELATORIO_C_S_T_OPCAO_1() {
        return RELATORIO_C_S_T_OPCAO_1;
    }

    public void setRELATORIO_C_S_T_OPCAO_1(int RELATORIO_C_S_T_OPCAO_1) {
        this.RELATORIO_C_S_T_OPCAO_1 = RELATORIO_C_S_T_OPCAO_1;
    }

    public int getRELATORIO_C_S_T_OPCAO_2() {
        return RELATORIO_C_S_T_OPCAO_2;
    }

    public void setRELATORIO_C_S_T_OPCAO_2(int RELATORIO_C_S_T_OPCAO_2) {
        this.RELATORIO_C_S_T_OPCAO_2 = RELATORIO_C_S_T_OPCAO_2;
    }

    public String getRELATORIO_C_S_T_N_DA_UC() {
        return RELATORIO_C_S_T_N_DA_UC;
    }

    public void setRELATORIO_C_S_T_N_DA_UC(String RELATORIO_C_S_T_N_DA_UC) {
        this.RELATORIO_C_S_T_N_DA_UC = RELATORIO_C_S_T_N_DA_UC;
    }

    public int getRELATORIO_RECURSOS_HIDRICOS_3() {
        return RELATORIO_RECURSOS_HIDRICOS_3;
    }

    public void setRELATORIO_RECURSOS_HIDRICOS_3(int RELATORIO_RECURSOS_HIDRICOS_3) {
        this.RELATORIO_RECURSOS_HIDRICOS_3 = RELATORIO_RECURSOS_HIDRICOS_3;
    }

    public String getRELATORIO_R_H_NOME_3() {
        return RELATORIO_R_H_NOME_3;
    }

    public void setRELATORIO_R_H_NOME_3(String RELATORIO_R_H_NOME_3) {
        this.RELATORIO_R_H_NOME_3 = RELATORIO_R_H_NOME_3;
    }

    public String getRELATORIO_R_H_DISTANCIA_3() {
        return RELATORIO_R_H_DISTANCIA_3;
    }

    public void setRELATORIO_R_H_DISTANCIA_3(String RELATORIO_R_H_DISTANCIA_3) {
        this.RELATORIO_R_H_DISTANCIA_3 = RELATORIO_R_H_DISTANCIA_3;
    }

    public String getRELATORIO_FONTES_DE_ABASTECIMENTO_AGUA() {
        return RELATORIO_FONTES_DE_ABASTECIMENTO_AGUA;
    }

    public void setRELATORIO_FONTES_DE_ABASTECIMENTO_AGUA(String RELATORIO_FONTES_DE_ABASTECIMENTO_AGUA) {
        this.RELATORIO_FONTES_DE_ABASTECIMENTO_AGUA = RELATORIO_FONTES_DE_ABASTECIMENTO_AGUA;
    }

    public String getRELATORIO_F_A_A_EMPRESA() {
        return RELATORIO_F_A_A_EMPRESA;
    }

    public void setRELATORIO_F_A_A_EMPRESA(String RELATORIO_F_A_A_EMPRESA) {
        this.RELATORIO_F_A_A_EMPRESA = RELATORIO_F_A_A_EMPRESA;
    }

    public String getRELATORIO_F_A_A_POCO_TIPO() {
        return RELATORIO_F_A_A_POCO_TIPO;
    }

    public void setRELATORIO_F_A_A_POCO_TIPO(String RELATORIO_F_A_A_POCO_TIPO) {
        this.RELATORIO_F_A_A_POCO_TIPO = RELATORIO_F_A_A_POCO_TIPO;
    }

    public String getRELATORIO_F_A_A_POCO_QTD() {
        return RELATORIO_F_A_A_POCO_QTD;
    }

    public void setRELATORIO_F_A_A_POCO_QTD(String RELATORIO_F_A_A_POCO_QTD) {
        this.RELATORIO_F_A_A_POCO_QTD = RELATORIO_F_A_A_POCO_QTD;
    }

    public String getRELATORIO_F_A_A_NUMERO_LICENCA() {
        return RELATORIO_F_A_A_NUMERO_LICENCA;
    }

    public void setRELATORIO_F_A_A_NUMERO_LICENCA(String RELATORIO_F_A_A_NUMERO_LICENCA) {
        this.RELATORIO_F_A_A_NUMERO_LICENCA = RELATORIO_F_A_A_NUMERO_LICENCA;
    }

    public String getRELATORIO_F_A_A_CURSO_DAGUA_NOME() {
        return RELATORIO_F_A_A_CURSO_DAGUA_NOME;
    }

    public void setRELATORIO_F_A_A_CURSO_DAGUA_NOME(String RELATORIO_F_A_A_CURSO_DAGUA_NOME) {
        this.RELATORIO_F_A_A_CURSO_DAGUA_NOME = RELATORIO_F_A_A_CURSO_DAGUA_NOME;
    }

    public String getRELATORIO_F_A_A_LAGO_NOME() {
        return RELATORIO_F_A_A_LAGO_NOME;
    }

    public void setRELATORIO_F_A_A_LAGO_NOME(String RELATORIO_F_A_A_LAGO_NOME) {
        this.RELATORIO_F_A_A_LAGO_NOME = RELATORIO_F_A_A_LAGO_NOME;
    }

    public String getRELATORIO_F_A_A_AGUAS_COSTEIRAS_ESPECIFICAR() {
        return RELATORIO_F_A_A_AGUAS_COSTEIRAS_ESPECIFICAR;
    }

    public void setRELATORIO_F_A_A_AGUAS_COSTEIRAS_ESPECIFICAR(String RELATORIO_F_A_A_AGUAS_COSTEIRAS_ESPECIFICAR) {
        this.RELATORIO_F_A_A_AGUAS_COSTEIRAS_ESPECIFICAR = RELATORIO_F_A_A_AGUAS_COSTEIRAS_ESPECIFICAR;
    }

    public String getRELATORIO_F_A_A_OUTRAS_ESPECIFICAR() {
        return RELATORIO_F_A_A_OUTRAS_ESPECIFICAR;
    }

    public void setRELATORIO_F_A_A_OUTRAS_ESPECIFICAR(String RELATORIO_F_A_A_OUTRAS_ESPECIFICAR) {
        this.RELATORIO_F_A_A_OUTRAS_ESPECIFICAR = RELATORIO_F_A_A_OUTRAS_ESPECIFICAR;
    }

    public String getRELATORIO_F_A_A_CONSUMO_DE_AGUA() {
        return RELATORIO_F_A_A_CONSUMO_DE_AGUA;
    }

    public void setRELATORIO_F_A_A_CONSUMO_DE_AGUA(String RELATORIO_F_A_A_CONSUMO_DE_AGUA) {
        this.RELATORIO_F_A_A_CONSUMO_DE_AGUA = RELATORIO_F_A_A_CONSUMO_DE_AGUA;
    }

    public String getRELATORIO_F_A_A_N_DOCUMENTO_OUTORGA_R_H() {
        return RELATORIO_F_A_A_N_DOCUMENTO_OUTORGA_R_H;
    }

    public void setRELATORIO_F_A_A_N_DOCUMENTO_OUTORGA_R_H(String RELATORIO_F_A_A_N_DOCUMENTO_OUTORGA_R_H) {
        this.RELATORIO_F_A_A_N_DOCUMENTO_OUTORGA_R_H = RELATORIO_F_A_A_N_DOCUMENTO_OUTORGA_R_H;
    }

    public String getRELATORIO_F_A_A_N_DOCUMENTO_CERTIDAO_D_O() {
        return RELATORIO_F_A_A_N_DOCUMENTO_CERTIDAO_D_O;
    }

    public void setRELATORIO_F_A_A_N_DOCUMENTO_CERTIDAO_D_O(String RELATORIO_F_A_A_N_DOCUMENTO_CERTIDAO_D_O) {
        this.RELATORIO_F_A_A_N_DOCUMENTO_CERTIDAO_D_O = RELATORIO_F_A_A_N_DOCUMENTO_CERTIDAO_D_O;
    }

    public String getRELATORIO_FONTES_DE_GERACAO_EFLUENTES() {
        return RELATORIO_FONTES_DE_GERACAO_EFLUENTES;
    }

    public void setRELATORIO_FONTES_DE_GERACAO_EFLUENTES(String RELATORIO_FONTES_DE_GERACAO_EFLUENTES) {
        this.RELATORIO_FONTES_DE_GERACAO_EFLUENTES = RELATORIO_FONTES_DE_GERACAO_EFLUENTES;
    }

    public int getRELATORIO_MOVIMENTACAO_DE_TERRA() {
        return RELATORIO_MOVIMENTACAO_DE_TERRA;
    }

    public void setRELATORIO_MOVIMENTACAO_DE_TERRA(int RELATORIO_MOVIMENTACAO_DE_TERRA) {
        this.RELATORIO_MOVIMENTACAO_DE_TERRA = RELATORIO_MOVIMENTACAO_DE_TERRA;
    }

    public String getRELATORIO_F_G_E_OUTRO_ESPECIFICAR_1() {
        return RELATORIO_F_G_E_OUTRO_ESPECIFICAR_1;
    }

    public void setRELATORIO_F_G_E_OUTRO_ESPECIFICAR_1(String RELATORIO_F_G_E_OUTRO_ESPECIFICAR_1) {
        this.RELATORIO_F_G_E_OUTRO_ESPECIFICAR_1 = RELATORIO_F_G_E_OUTRO_ESPECIFICAR_1;
    }

    public String getRELATORIO_F_G_E_OUTRO_ESPECIFICAR_2() {
        return RELATORIO_F_G_E_OUTRO_ESPECIFICAR_2;
    }

    public void setRELATORIO_F_G_E_OUTRO_ESPECIFICAR_2(String RELATORIO_F_G_E_OUTRO_ESPECIFICAR_2) {
        this.RELATORIO_F_G_E_OUTRO_ESPECIFICAR_2 = RELATORIO_F_G_E_OUTRO_ESPECIFICAR_2;
    }

    public String getRELATORIO_MANUTENCAO_DO_SISTEMA_DE_TRATAMENTO() {
        return RELATORIO_MANUTENCAO_DO_SISTEMA_DE_TRATAMENTO;
    }

    public void setRELATORIO_MANUTENCAO_DO_SISTEMA_DE_TRATAMENTO(String RELATORIO_MANUTENCAO_DO_SISTEMA_DE_TRATAMENTO) {
        this.RELATORIO_MANUTENCAO_DO_SISTEMA_DE_TRATAMENTO = RELATORIO_MANUTENCAO_DO_SISTEMA_DE_TRATAMENTO;
    }

    public String getRELATORIO_M_S_T_ESPECIFICAR() {
        return RELATORIO_M_S_T_ESPECIFICAR;
    }

    public void setRELATORIO_M_S_T_ESPECIFICAR(String RELATORIO_M_S_T_ESPECIFICAR) {
        this.RELATORIO_M_S_T_ESPECIFICAR = RELATORIO_M_S_T_ESPECIFICAR;
    }

    public String getRELATORIO_M_S_T_CAIXA_DE_GORDURA() {
        return RELATORIO_M_S_T_CAIXA_DE_GORDURA;
    }

    public void setRELATORIO_M_S_T_CAIXA_DE_GORDURA(String RELATORIO_M_S_T_CAIXA_DE_GORDURA) {
        this.RELATORIO_M_S_T_CAIXA_DE_GORDURA = RELATORIO_M_S_T_CAIXA_DE_GORDURA;
    }

    public String getRELATORIO_M_S_T_CAIXA_DE_GORDURA_ESPECIFICAR() {
        return RELATORIO_M_S_T_CAIXA_DE_GORDURA_ESPECIFICAR;
    }

    public void setRELATORIO_M_S_T_CAIXA_DE_GORDURA_ESPECIFICAR(String RELATORIO_M_S_T_CAIXA_DE_GORDURA_ESPECIFICAR) {
        this.RELATORIO_M_S_T_CAIXA_DE_GORDURA_ESPECIFICAR = RELATORIO_M_S_T_CAIXA_DE_GORDURA_ESPECIFICAR;
    }

    public String getRELATORIO_GERENCIAMENTO_DE_RESIDUOS() {
        return RELATORIO_GERENCIAMENTO_DE_RESIDUOS;
    }

    public void setRELATORIO_GERENCIAMENTO_DE_RESIDUOS(String RELATORIO_GERENCIAMENTO_DE_RESIDUOS) {
        this.RELATORIO_GERENCIAMENTO_DE_RESIDUOS = RELATORIO_GERENCIAMENTO_DE_RESIDUOS;
    }

    public String getRELATORIO_G_R_ESPECIFICAR_1() {
        return RELATORIO_G_R_ESPECIFICAR_1;
    }

    public void setRELATORIO_G_R_ESPECIFICAR_1(String RELATORIO_G_R_ESPECIFICAR_1) {
        this.RELATORIO_G_R_ESPECIFICAR_1 = RELATORIO_G_R_ESPECIFICAR_1;
    }

    public String getRELATORIO_G_R_ESPECIFICAR_2() {
        return RELATORIO_G_R_ESPECIFICAR_2;
    }

    public void setRELATORIO_G_R_ESPECIFICAR_2(String RELATORIO_G_R_ESPECIFICAR_2) {
        this.RELATORIO_G_R_ESPECIFICAR_2 = RELATORIO_G_R_ESPECIFICAR_2;
    }

    public String getRELATORIO_G_R_ESPECIFICAR_3() {
        return RELATORIO_G_R_ESPECIFICAR_3;
    }

    public void setRELATORIO_G_R_ESPECIFICAR_3(String RELATORIO_G_R_ESPECIFICAR_3) {
        this.RELATORIO_G_R_ESPECIFICAR_3 = RELATORIO_G_R_ESPECIFICAR_3;
    }

    public String getRELATORIO_G_R_NOME_1() {
        return RELATORIO_G_R_NOME_1;
    }

    public void setRELATORIO_G_R_NOME_1(String RELATORIO_G_R_NOME_1) {
        this.RELATORIO_G_R_NOME_1 = RELATORIO_G_R_NOME_1;
    }

    public String getRELATORIO_G_R_NOME_2() {
        return RELATORIO_G_R_NOME_2;
    }

    public void setRELATORIO_G_R_NOME_2(String RELATORIO_G_R_NOME_2) {
        this.RELATORIO_G_R_NOME_2 = RELATORIO_G_R_NOME_2;
    }

    public String getRELATORIO_G_R_NOME_3() {
        return RELATORIO_G_R_NOME_3;
    }

    public void setRELATORIO_G_R_NOME_3(String RELATORIO_G_R_NOME_3) {
        this.RELATORIO_G_R_NOME_3 = RELATORIO_G_R_NOME_3;
    }

    public String getRELATORIO_G_R_NUMERO_LICENCA_1() {
        return RELATORIO_G_R_NUMERO_LICENCA_1;
    }

    public void setRELATORIO_G_R_NUMERO_LICENCA_1(String RELATORIO_G_R_NUMERO_LICENCA_1) {
        this.RELATORIO_G_R_NUMERO_LICENCA_1 = RELATORIO_G_R_NUMERO_LICENCA_1;
    }

    public String getRELATORIO_G_R_NUMERO_LICENCA_2() {
        return RELATORIO_G_R_NUMERO_LICENCA_2;
    }

    public void setRELATORIO_G_R_NUMERO_LICENCA_2(String RELATORIO_G_R_NUMERO_LICENCA_2) {
        this.RELATORIO_G_R_NUMERO_LICENCA_2 = RELATORIO_G_R_NUMERO_LICENCA_2;
    }

    public String getRELATORIO_G_R_NUMERO_LICENCA_3() {
        return RELATORIO_G_R_NUMERO_LICENCA_3;
    }

    public void setRELATORIO_G_R_NUMERO_LICENCA_3(String RELATORIO_G_R_NUMERO_LICENCA_3) {
        this.RELATORIO_G_R_NUMERO_LICENCA_3 = RELATORIO_G_R_NUMERO_LICENCA_3;
    }

    public String getRELATORIO_G_R_CONSUMEO_DE_AGUA_L_DIA() {
        return RELATORIO_G_R_CONSUMEO_DE_AGUA_L_DIA;
    }

    public void setRELATORIO_G_R_CONSUMEO_DE_AGUA_L_DIA(String RELATORIO_G_R_CONSUMEO_DE_AGUA_L_DIA) {
        this.RELATORIO_G_R_CONSUMEO_DE_AGUA_L_DIA = RELATORIO_G_R_CONSUMEO_DE_AGUA_L_DIA;
    }

    public String getRELATORIO_G_R_CONSUMEO_DE_AGUA_M_MES() {
        return RELATORIO_G_R_CONSUMEO_DE_AGUA_M_MES;
    }

    public void setRELATORIO_G_R_CONSUMEO_DE_AGUA_M_MES(String RELATORIO_G_R_CONSUMEO_DE_AGUA_M_MES) {
        this.RELATORIO_G_R_CONSUMEO_DE_AGUA_M_MES = RELATORIO_G_R_CONSUMEO_DE_AGUA_M_MES;
    }

    public String getRELATORIO_EMISSOES_ATMOSFERICAS() {
        return RELATORIO_EMISSOES_ATMOSFERICAS;
    }

    public void setRELATORIO_EMISSOES_ATMOSFERICAS(String RELATORIO_EMISSOES_ATMOSFERICAS) {
        this.RELATORIO_EMISSOES_ATMOSFERICAS = RELATORIO_EMISSOES_ATMOSFERICAS;
    }

    public String getRELATORIO_E_A_ESPECIFICAR() {
        return RELATORIO_E_A_ESPECIFICAR;
    }

    public void setRELATORIO_E_A_ESPECIFICAR(String RELATORIO_E_A_ESPECIFICAR) {
        this.RELATORIO_E_A_ESPECIFICAR = RELATORIO_E_A_ESPECIFICAR;
    }

    public String getRELATORIO_ROTEIRO_DE_ACESSO() {
        return RELATORIO_ROTEIRO_DE_ACESSO;
    }

    public void setRELATORIO_ROTEIRO_DE_ACESSO(String RELATORIO_ROTEIRO_DE_ACESSO) {
        this.RELATORIO_ROTEIRO_DE_ACESSO = RELATORIO_ROTEIRO_DE_ACESSO;
    }

    public String getRELATORIO_CROQUI_DE_LOCALIZACAO_EMPREENDIMENTO() {
        return RELATORIO_CROQUI_DE_LOCALIZACAO_EMPREENDIMENTO;
    }

    public void setRELATORIO_CROQUI_DE_LOCALIZACAO_EMPREENDIMENTO(String RELATORIO_CROQUI_DE_LOCALIZACAO_EMPREENDIMENTO) {
        this.RELATORIO_CROQUI_DE_LOCALIZACAO_EMPREENDIMENTO = RELATORIO_CROQUI_DE_LOCALIZACAO_EMPREENDIMENTO;
    }

    public int getRELATORIO_CROQUI_PERGUNTA() {
        return RELATORIO_CROQUI_PERGUNTA;
    }

    public void setRELATORIO_CROQUI_PERGUNTA(int RELATORIO_CROQUI_PERGUNTA) {
        this.RELATORIO_CROQUI_PERGUNTA = RELATORIO_CROQUI_PERGUNTA;
    }

    public String getRELATORIO_TEXTO_ANEXO() {
        return RELATORIO_TEXTO_ANEXO;
    }

    public void setRELATORIO_TEXTO_ANEXO(String RELATORIO_TEXTO_ANEXO) {
        this.RELATORIO_TEXTO_ANEXO = RELATORIO_TEXTO_ANEXO;
    }

    public Calendar getRELATORIO_DATA_ATUAL() {
        return RELATORIO_DATA_ATUAL;
    }

    public void setRELATORIO_DATA_ATUAL(Calendar RELATORIO_DATA_ATUAL) {
        this.RELATORIO_DATA_ATUAL = RELATORIO_DATA_ATUAL;
    }

    public int getPROFISSIONAL_ID() {
        return PROFISSIONAL_ID;
    }

    public void setPROFISSIONAL_ID(int PROFISSIONAL_ID) {
        this.PROFISSIONAL_ID = PROFISSIONAL_ID;
    }

    public int getCATEGORIA_ID() {
        return CATEGORIA_ID;
    }

    public void setCATEGORIA_ID(int CATEGORIA_ID) {
        this.CATEGORIA_ID = CATEGORIA_ID;
    }

    public String getCLIENTE_NOME() {
        return CLIENTE_NOME;
    }

    public void setCLIENTE_NOME(String CLIENTE_NOME) {
        this.CLIENTE_NOME = CLIENTE_NOME;
    }

    public String getCLIENTE_FANTASIA() {
        return CLIENTE_FANTASIA;
    }

    public void setCLIENTE_FANTASIA(String CLIENTE_FANTASIA) {
        this.CLIENTE_FANTASIA = CLIENTE_FANTASIA;
    }

    public String getCLIENTE_ENDERECO() {
        return CLIENTE_ENDERECO;
    }

    public void setCLIENTE_ENDERECO(String CLIENTE_ENDERECO) {
        this.CLIENTE_ENDERECO = CLIENTE_ENDERECO;
    }

    public String getCLIENTE_MUNICIPIO() {
        return CLIENTE_MUNICIPIO;
    }

    public void setCLIENTE_MUNICIPIO(String CLIENTE_MUNICIPIO) {
        this.CLIENTE_MUNICIPIO = CLIENTE_MUNICIPIO;
    }

    public String getCLIENTE_NUMERO() {
        return CLIENTE_NUMERO;
    }

    public void setCLIENTE_NUMERO(String CLIENTE_NUMERO) {
        this.CLIENTE_NUMERO = CLIENTE_NUMERO;
    }

    public String getCLIENTE_BAIRRO() {
        return CLIENTE_BAIRRO;
    }

    public void setCLIENTE_BAIRRO(String CLIENTE_BAIRRO) {
        this.CLIENTE_BAIRRO = CLIENTE_BAIRRO;
    }

    public String getCLIENTE_TELEFONE() {
        return CLIENTE_TELEFONE;
    }

    public void setCLIENTE_TELEFONE(String CLIENTE_TELEFONE) {
        this.CLIENTE_TELEFONE = CLIENTE_TELEFONE;
    }

    public String getCLIENTE_CELULAR() {
        return CLIENTE_CELULAR;
    }

    public void setCLIENTE_CELULAR(String CLIENTE_CELULAR) {
        this.CLIENTE_CELULAR = CLIENTE_CELULAR;
    }

    public String getCLIENTE_CEP() {
        return CLIENTE_CEP;
    }

    public void setCLIENTE_CEP(String CLIENTE_CEP) {
        this.CLIENTE_CEP = CLIENTE_CEP;
    }

    public String getCLIENTE_CPF() {
        return CLIENTE_CPF;
    }

    public void setCLIENTE_CPF(String CLIENTE_CPF) {
        this.CLIENTE_CPF = CLIENTE_CPF;
    }

    public String getCLIENTE_CNPJ() {
        return CLIENTE_CNPJ;
    }

    public void setCLIENTE_CNPJ(String CLIENTE_CNPJ) {
        this.CLIENTE_CNPJ = CLIENTE_CNPJ;
    }

    public String getCLIENTE_UTMN() {
        return CLIENTE_UTMN;
    }

    public void setCLIENTE_UTMN(String CLIENTE_UTMN) {
        this.CLIENTE_UTMN = CLIENTE_UTMN;
    }

    public String getCLIENTE_UTME() {
        return CLIENTE_UTME;
    }

    public void setCLIENTE_UTME(String CLIENTE_UTME) {
        this.CLIENTE_UTME = CLIENTE_UTME;
    }

    public Calendar getCLIENTE_DATA() {
        return CLIENTE_DATA;
    }

    public void setCLIENTE_DATA(Calendar CLIENTE_DATA) {
        this.CLIENTE_DATA = CLIENTE_DATA;
    }

    public String getPROFISSIONAL_NOME() {
        return PROFISSIONAL_NOME;
    }

    public void setPROFISSIONAL_NOME(String PROFISSIONAL_NOME) {
        this.PROFISSIONAL_NOME = PROFISSIONAL_NOME;
    }

    public String getCATEGORIA_NOME() {
        return CATEGORIA_NOME;
    }

    public void setCATEGORIA_NOME(String CATEGORIA_NOME) {
        this.CATEGORIA_NOME = CATEGORIA_NOME;
    }

    public int getREPRESENTANTE_ID() {
        return REPRESENTANTE_ID;
    }

    public void setREPRESENTANTE_ID(int REPRESENTANTE_ID) {
        this.REPRESENTANTE_ID = REPRESENTANTE_ID;
    }

    public String getREPRESENTANTE_NOME() {
        return REPRESENTANTE_NOME;
    }

    public void setREPRESENTANTE_NOME(String REPRESENTANTE_NOME) {
        this.REPRESENTANTE_NOME = REPRESENTANTE_NOME;
    }

   
}
