/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import bancodedados.ProfissionalBD;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.tabelas.ModeloTabelaProfissionais;
import modelos.Profissional;

/**
 *
 * @author Jean
 */
public class jifAbasProfissionais extends javax.swing.JInternalFrame {

    /**
     * Creates new form jifAbasClientes
     */
    /**
     * Objetos temporarios
     */
    Profissional profissionalCadastro = new Profissional();

    /**
     * Definição de ArrayList's
     */
    ArrayList<Profissional> listaOriginalTemporariaProfissional = new ArrayList();

    /**
     * Classes de definição de modelos de tabela
     */
    ModeloTabelaProfissionais modeloTabelaProfissional = new ModeloTabelaProfissionais();

    /**
     * Classes de conexão com o banco
     */
    ProfissionalBD conexaoTabelaProfissionais = new ProfissionalBD();

    public jifAbasProfissionais() {
        initComponents();

        tbProfissionaisCadastrados.setModel(modeloTabelaProfissional);

        //----------------buscas na tabela--------------------------------------
        buscarProfissionaisTabela();

        //----------------Desabilitar bostoes cancelar atualização--------------
        btCancelarAtualizacaoProfissional.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tpnAbasProfissionais = new javax.swing.JTabbedPane();
        pnCadastrarNovoProfissional = new javax.swing.JPanel();
        btCancelarAtualizacaoProfissional = new javax.swing.JButton();
        btFinalizarCadastroProfissional = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfProfissionalNome = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tfProfissionalProfissao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfProfissionalCpf = new javax.swing.JFormattedTextField();
        tfProfissionalCrea = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfProfissionalCep = new javax.swing.JFormattedTextField();
        tfProfissionalRua = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfProfissionalNumero = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfProfissionalBairro = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfProfissionalCidade = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cbProfissionalEstado = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        tfProfissionalTelefone = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        tfProfissionalCelular = new javax.swing.JFormattedTextField();
        tfProfissionalCtma = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfProfissionalRCC = new javax.swing.JTextField();
        pnGerenciarProfissionais = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfPalavraChaveProfissional = new javax.swing.JTextField();
        ckbProfissionalCpf = new javax.swing.JCheckBox();
        ckbProfissionalNome = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbProfissionaisCadastrados = new javax.swing.JTable();
        btExcluirProfissional = new javax.swing.JButton();
        btEditarProfissional = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Profissional");
        setPreferredSize(new java.awt.Dimension(600, 600));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(600, 600));

        tpnAbasProfissionais.setPreferredSize(new java.awt.Dimension(600, 600));

        pnCadastrarNovoProfissional.setPreferredSize(new java.awt.Dimension(600, 590));

        btCancelarAtualizacaoProfissional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_edit-not-validated_85308.png"))); // NOI18N
        btCancelarAtualizacaoProfissional.setToolTipText("Cancelar Atualização");
        btCancelarAtualizacaoProfissional.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCancelarAtualizacaoProfissional.setPreferredSize(new java.awt.Dimension(150, 150));
        btCancelarAtualizacaoProfissional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarAtualizacaoProfissionalActionPerformed(evt);
            }
        });

        btFinalizarCadastroProfissional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/complete-file.png"))); // NOI18N
        btFinalizarCadastroProfissional.setToolTipText("Cadastrar");
        btFinalizarCadastroProfissional.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btFinalizarCadastroProfissional.setPreferredSize(new java.awt.Dimension(150, 150));
        btFinalizarCadastroProfissional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinalizarCadastroProfissionalActionPerformed(evt);
            }
        });

        jLabel7.setText("Profisisonal:");

        jLabel20.setText("Profissão:");

        tfProfissionalProfissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProfissionalProfissaoActionPerformed(evt);
            }
        });

        jLabel8.setText("CPF:");

        try {
            tfProfissionalCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        tfProfissionalCrea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProfissionalCreaActionPerformed(evt);
            }
        });

        jLabel21.setText("CREA:");

        jLabel14.setText("CEP:");

        try {
            tfProfissionalCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel15.setText("Rua:");

        jLabel11.setText("Número:");

        tfProfissionalNumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel16.setText("Bairro:");

        tfProfissionalBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProfissionalBairroActionPerformed(evt);
            }
        });

        jLabel17.setText("Cidade:");

        jLabel18.setText("Estado:");

        cbProfissionalEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jLabel19.setText("Telefone:");

        try {
            tfProfissionalTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel10.setText("Celular:");

        try {
            tfProfissionalCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        tfProfissionalCtma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProfissionalCtmaActionPerformed(evt);
            }
        });

        jLabel2.setText("CTMA:");

        jLabel3.setText(" Registro no Conselho de Classe:");

        javax.swing.GroupLayout pnCadastrarNovoProfissionalLayout = new javax.swing.GroupLayout(pnCadastrarNovoProfissional);
        pnCadastrarNovoProfissional.setLayout(pnCadastrarNovoProfissionalLayout);
        pnCadastrarNovoProfissionalLayout.setHorizontalGroup(
            pnCadastrarNovoProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadastrarNovoProfissionalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btCancelarAtualizacaoProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btFinalizarCadastroProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(pnCadastrarNovoProfissionalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnCadastrarNovoProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCadastrarNovoProfissionalLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfProfissionalRCC, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnCadastrarNovoProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnCadastrarNovoProfissionalLayout.createSequentialGroup()
                            .addGroup(pnCadastrarNovoProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(49, 49, 49)
                            .addComponent(tfProfissionalCtma, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnCadastrarNovoProfissionalLayout.createSequentialGroup()
                            .addGroup(pnCadastrarNovoProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel20))
                            .addGap(18, 18, 18)
                            .addGroup(pnCadastrarNovoProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(pnCadastrarNovoProfissionalLayout.createSequentialGroup()
                                    .addComponent(tfProfissionalCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfProfissionalCrea, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tfProfissionalNome, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfProfissionalProfissao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pnCadastrarNovoProfissionalLayout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(61, 61, 61)
                            .addComponent(tfProfissionalCep, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(39, 39, 39)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfProfissionalRua))
                        .addGroup(pnCadastrarNovoProfissionalLayout.createSequentialGroup()
                            .addGroup(pnCadastrarNovoProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19))
                            .addGap(25, 25, 25)
                            .addGroup(pnCadastrarNovoProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnCadastrarNovoProfissionalLayout.createSequentialGroup()
                                    .addComponent(tfProfissionalNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(jLabel16)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfProfissionalBairro))
                                .addGroup(pnCadastrarNovoProfissionalLayout.createSequentialGroup()
                                    .addGroup(pnCadastrarNovoProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfProfissionalCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfProfissionalTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnCadastrarNovoProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(pnCadastrarNovoProfissionalLayout.createSequentialGroup()
                                            .addComponent(jLabel18)
                                            .addGap(16, 16, 16)
                                            .addComponent(cbProfissionalEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(73, 73, 73))
                                        .addGroup(pnCadastrarNovoProfissionalLayout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tfProfissionalCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        pnCadastrarNovoProfissionalLayout.setVerticalGroup(
            pnCadastrarNovoProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadastrarNovoProfissionalLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(pnCadastrarNovoProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfProfissionalNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnCadastrarNovoProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfProfissionalProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnCadastrarNovoProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfProfissionalCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(tfProfissionalCrea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnCadastrarNovoProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfProfissionalCtma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnCadastrarNovoProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfProfissionalCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfProfissionalRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnCadastrarNovoProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfProfissionalNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(tfProfissionalBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnCadastrarNovoProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tfProfissionalCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(cbProfissionalEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnCadastrarNovoProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfProfissionalTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(tfProfissionalCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCadastrarNovoProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfProfissionalRCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(pnCadastrarNovoProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCancelarAtualizacaoProfissional, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFinalizarCadastroProfissional, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        tpnAbasProfissionais.addTab("Cadastrar Novos Profissionais", pnCadastrarNovoProfissional);

        pnGerenciarProfissionais.setPreferredSize(new java.awt.Dimension(600, 600));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtro de Busca", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setText("Palavra-chave:");

        tfPalavraChaveProfissional.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPalavraChaveProfissionalKeyReleased(evt);
            }
        });

        ckbProfissionalCpf.setText("CPF");

        ckbProfissionalNome.setText("NOME");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfPalavraChaveProfissional)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ckbProfissionalCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ckbProfissionalNome)
                        .addGap(192, 192, 192)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfPalavraChaveProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbProfissionalCpf)
                    .addComponent(ckbProfissionalNome))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        tbProfissionaisCadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbProfissionaisCadastrados);

        btExcluirProfissional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete-file.png"))); // NOI18N
        btExcluirProfissional.setToolTipText("Excluir");
        btExcluirProfissional.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btExcluirProfissional.setPreferredSize(new java.awt.Dimension(150, 150));
        btExcluirProfissional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirProfissionalActionPerformed(evt);
            }
        });

        btEditarProfissional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/edit-file.png"))); // NOI18N
        btEditarProfissional.setToolTipText("Editar");
        btEditarProfissional.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btEditarProfissional.setPreferredSize(new java.awt.Dimension(150, 150));
        btEditarProfissional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarProfissionalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnGerenciarProfissionaisLayout = new javax.swing.GroupLayout(pnGerenciarProfissionais);
        pnGerenciarProfissionais.setLayout(pnGerenciarProfissionaisLayout);
        pnGerenciarProfissionaisLayout.setHorizontalGroup(
            pnGerenciarProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGerenciarProfissionaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnGerenciarProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnGerenciarProfissionaisLayout.createSequentialGroup()
                        .addComponent(btExcluirProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btEditarProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        pnGerenciarProfissionaisLayout.setVerticalGroup(
            pnGerenciarProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGerenciarProfissionaisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnGerenciarProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEditarProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluirProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        tpnAbasProfissionais.addTab("Gerenciar Profissionais", pnGerenciarProfissionais);

        jScrollPane1.setViewportView(tpnAbasProfissionais);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
        );

        setBounds(0, 0, 600, 600);
    }// </editor-fold>//GEN-END:initComponents

    public void buscarProfissionaisTabela() {
        modeloTabelaProfissional.inserirListaProfissionais(conexaoTabelaProfissionais.selecionarTodosProfissionais());
        listaOriginalTemporariaProfissional = modeloTabelaProfissional.retornaListaProfissionais();
        tbProfissionaisCadastrados.updateUI();
    }

    public Profissional preencherDadosCadastroProfissional() {

        profissionalCadastro.setProfissional_nome(tfProfissionalNome.getText());
        profissionalCadastro.setProfissional_profissao(tfProfissionalProfissao.getText());
        profissionalCadastro.setProfissional_cpf(tfProfissionalCpf.getText());
        profissionalCadastro.setProfissional_crea(tfProfissionalCrea.getText());
        profissionalCadastro.setProfissional_ctma(tfProfissionalCtma.getText());
        profissionalCadastro.setProfissional_cep(tfProfissionalCep.getText());
        profissionalCadastro.setProfissional_endereco(tfProfissionalRua.getText());
        profissionalCadastro.setProfissional_numero(tfProfissionalNumero.getText());
        profissionalCadastro.setProfissional_bairro(tfProfissionalBairro.getText());
        profissionalCadastro.setProfissional_cidade(tfProfissionalCidade.getText());
        profissionalCadastro.setProfissional_estado(cbProfissionalEstado.getSelectedItem().toString());
        profissionalCadastro.setProfissional_telefone(tfProfissionalTelefone.getText());
        profissionalCadastro.setProfissional_celular(tfProfissionalCelular.getText());
        profissionalCadastro.setProfissional_rcc(tfProfissionalRCC.getText());

        return profissionalCadastro;

    }

    public void limparCamposCadastroProfissional() {
        tfProfissionalNome.setText("");
        tfProfissionalProfissao.setText("");
        tfProfissionalCpf.setText("");
        tfProfissionalCrea.setText("");
        tfProfissionalCtma.setText("");
        tfProfissionalCep.setText("");
        tfProfissionalRua.setText("");
        tfProfissionalNumero.setText("");
        tfProfissionalBairro.setText("");
        tfProfissionalCidade.setText("");
        cbProfissionalEstado.setSelectedIndex(0);
        tfProfissionalTelefone.setText("");
        tfProfissionalCelular.setText("");
        tfProfissionalRCC.setText("");
        tpnAbasProfissionais.setTitleAt(0, "Cadastrar Novos Profissionais");
        btFinalizarCadastroProfissional.setToolTipText("Cadastrar");
        tpnAbasProfissionais.setEnabledAt(1, true);
        tpnAbasProfissionais.setSelectedIndex(1);
        btCancelarAtualizacaoProfissional.setVisible(false);

    }

    private void tfPalavraChaveProfissionalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPalavraChaveProfissionalKeyReleased
        // TODO add your handling code here:
        if (tfPalavraChaveProfissional.getText().isEmpty()) {
            modeloTabelaProfissional.inserirListaProfissionais(conexaoTabelaProfissionais.selecionarTodosProfissionais());
        } else {

            modeloTabelaProfissional.inserirListaProfissionais(conexaoTabelaProfissionais.selecionarTodosProfissionais());
            listaOriginalTemporariaProfissional.clear();

            if (ckbProfissionalCpf.isSelected()) {
                for (int i = 0; i < modeloTabelaProfissional.retornaListaProfissionais().size(); i++) {
                    if (modeloTabelaProfissional.retornaListaProfissionais().get(i).getProfissional_cpf().toLowerCase().contains(tfPalavraChaveProfissional.getText().toLowerCase())) {
                        listaOriginalTemporariaProfissional.add(modeloTabelaProfissional.retornaListaProfissionais().get(i));
                    }
                }
            } else if (ckbProfissionalNome.isSelected()) {
                for (int i = 0; i < modeloTabelaProfissional.retornaListaProfissionais().size(); i++) {
                    if (modeloTabelaProfissional.retornaListaProfissionais().get(i).getProfissional_nome().toLowerCase().contains(tfPalavraChaveProfissional.getText().toLowerCase())) {
                        listaOriginalTemporariaProfissional.add(modeloTabelaProfissional.retornaListaProfissionais().get(i));
                    }
                }
            }

            modeloTabelaProfissional.inserirListaProfissionais(listaOriginalTemporariaProfissional);

        }

        tbProfissionaisCadastrados.updateUI();


    }//GEN-LAST:event_tfPalavraChaveProfissionalKeyReleased

    private void btExcluirProfissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirProfissionalActionPerformed
        // TODO add your handling code here:
        if (tbProfissionaisCadastrados.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(rootPane, "Não existem clientes selecionados para serem deletados");
        } else if (tbProfissionaisCadastrados.getRowCount() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Não existem mais clientes para serem deletados");
        } else if (JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir esse cliente?", "Excluir cliente", 0) == 0) {
            if (tbProfissionaisCadastrados.getSelectedRow() != -1) {
                conexaoTabelaProfissionais.removerProfissional(modeloTabelaProfissional.retornaListaProfissionais().get(tbProfissionaisCadastrados.getSelectedRow()).getProfissional_id(), tbProfissionaisCadastrados.getValueAt(tbProfissionaisCadastrados.getSelectedRow(), 0).toString());
                modeloTabelaProfissional.inserirListaProfissionais(conexaoTabelaProfissionais.selecionarTodosProfissionais());

                tbProfissionaisCadastrados.updateUI();
            }
        }
    }//GEN-LAST:event_btExcluirProfissionalActionPerformed

    private void btEditarProfissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarProfissionalActionPerformed
        // TODO add your handling code here:
        if (tbProfissionaisCadastrados.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(rootPane, "Não existem profissionais selecionados para serem editados");
        } else {

            Profissional profissional = modeloTabelaProfissional.retornaListaProfissionais().get(tbProfissionaisCadastrados.getSelectedRow());

            tfProfissionalNome.setText(profissional.getProfissional_nome());
            tfProfissionalProfissao.setText(profissional.getProfissional_profissao());
            tfProfissionalCpf.setText(profissional.getProfissional_cpf());
            tfProfissionalCrea.setText(profissional.getProfissional_crea());
            tfProfissionalCtma.setText(profissional.getProfissional_ctma());
            tfProfissionalCep.setText(profissional.getProfissional_cep());
            tfProfissionalRua.setText(profissional.getProfissional_endereco());
            tfProfissionalNumero.setText(profissional.getProfissional_numero());
            tfProfissionalBairro.setText(profissional.getProfissional_bairro());
            tfProfissionalCidade.setText(profissional.getProfissional_cidade());
            cbProfissionalEstado.setSelectedItem(profissional.getProfissional_estado());
            tfProfissionalTelefone.setText(profissional.getProfissional_telefone());
            tfProfissionalCelular.setText(profissional.getProfissional_celular());
            tfProfissionalRCC.setText(profissional.getProfissional_rcc());

            tpnAbasProfissionais.setSelectedIndex(0); // Mudando para a PRIMEIRA aba

            btFinalizarCadastroProfissional.setToolTipText("Atualizar");
            tpnAbasProfissionais.setTitleAt(0, "Atualizar dados");
            tpnAbasProfissionais.setEnabledAt(1, false);
            btCancelarAtualizacaoProfissional.setVisible(true);
        }
    }//GEN-LAST:event_btEditarProfissionalActionPerformed

    private void tfProfissionalCtmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProfissionalCtmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProfissionalCtmaActionPerformed

    private void tfProfissionalProfissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProfissionalProfissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProfissionalProfissaoActionPerformed

    private void btFinalizarCadastroProfissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinalizarCadastroProfissionalActionPerformed
        // TODO add your handling code here:
       if (tfProfissionalNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(pnCadastrarNovoProfissional, "Por favor insira o nome do profissional", "Aviso", 2);
            tfProfissionalNome.requestFocus();
        } else {
            if (tfProfissionalProfissao.getText().isEmpty()) {
                JOptionPane.showMessageDialog(pnCadastrarNovoProfissional, "Por favor insira a profissão do profissional", "Aviso", 2);
                tfProfissionalNome.requestFocus();
            } else {
                if (tfProfissionalCpf.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(pnCadastrarNovoProfissional, "Por favor insira o cpf do profissional", "Aviso", 2);
                    tfProfissionalCpf.requestFocus();
                } else {
                    if (tfProfissionalCrea.getText().isEmpty()) {
                        JOptionPane.showMessageDialog(pnCadastrarNovoProfissional, "Por favor insira o crea do profissional", "Aviso", 2);
                        tfProfissionalCrea.requestFocus();
                    } else {
                        if (tfProfissionalCtma.getText().isEmpty()) {
                            JOptionPane.showMessageDialog(pnCadastrarNovoProfissional, "Por favor insira o ctma do profissional", "Aviso", 2);
                            tfProfissionalCtma.requestFocus();
                        } else {
                            if (tfProfissionalCep.getText().isEmpty()) {
                                JOptionPane.showMessageDialog(pnCadastrarNovoProfissional, "Por favor insira o cep do profissional", "Aviso", 2);
                                tfProfissionalCep.requestFocus();
                            } else {
                                if (tfProfissionalRua.getText().isEmpty()) {
                                    JOptionPane.showMessageDialog(pnCadastrarNovoProfissional, "Por favor insira a rua do profissional", "Aviso", 2);
                                    tfProfissionalRua.requestFocus();
                                } else {
                                    if (tfProfissionalBairro.getText().isEmpty()) {
                                        JOptionPane.showMessageDialog(pnCadastrarNovoProfissional, "Por favor insira o bairro do profissional", "Aviso", 2);
                                        tfProfissionalBairro.requestFocus();
                                    } else {
                                        if (tfProfissionalCidade.getText().isEmpty()) {
                                            JOptionPane.showMessageDialog(pnCadastrarNovoProfissional, "Por favor insira a cidade do profisisonal", "Aviso", 2);
                                            tfProfissionalCidade.requestFocus();
                                        } else {

                                            if (cbProfissionalEstado.getSelectedIndex() == 0) {
                                                JOptionPane.showMessageDialog(pnCadastrarNovoProfissional, "Por favor insira o estado do profissional", "Aviso", 2);
                                                cbProfissionalEstado.requestFocus();
                                            } else {
                                                if (btFinalizarCadastroProfissional.getToolTipText().equals("Cadastrar")) {
                                                    conexaoTabelaProfissionais.inserirNovoProfissional(preencherDadosCadastroProfissional());
                                                    buscarProfissionaisTabela();
                                                    limparCamposCadastroProfissional();
                                                } else {
                                                    conexaoTabelaProfissionais.alterarProfissional(modeloTabelaProfissional.retornaListaProfissionais().get(tbProfissionaisCadastrados.getSelectedRow()).getProfissional_id(), preencherDadosCadastroProfissional());

                                                    buscarProfissionaisTabela();

                                                    limparCamposCadastroProfissional();
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }

            }
        }


    }//GEN-LAST:event_btFinalizarCadastroProfissionalActionPerformed

    private void btCancelarAtualizacaoProfissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarAtualizacaoProfissionalActionPerformed
        // TODO add your handling code here:
        btFinalizarCadastroProfissional.setToolTipText("Cadastrar");
        btCancelarAtualizacaoProfissional.setVisible(false);
        tpnAbasProfissionais.setEnabledAt(1, true);
        tpnAbasProfissionais.setSelectedIndex(1);
        tpnAbasProfissionais.setTitleAt(0, "Cadastrar Novos Profissionais");
        tfProfissionalNome.setText("");
        tfProfissionalProfissao.setText("");
        tfProfissionalCpf.setText("");
        tfProfissionalCrea.setText("");
        tfProfissionalCtma.setText("");
        tfProfissionalCep.setText("");
        tfProfissionalRua.setText("");
        tfProfissionalNumero.setText("");
        tfProfissionalBairro.setText("");
        tfProfissionalCidade.setText("");
        cbProfissionalEstado.setSelectedIndex(0);
        tfProfissionalTelefone.setText("");
        tfProfissionalCelular.setText("");
        tfProfissionalRCC.setText("");
    }//GEN-LAST:event_btCancelarAtualizacaoProfissionalActionPerformed

    private void tfProfissionalBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProfissionalBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProfissionalBairroActionPerformed

    private void tfProfissionalCreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProfissionalCreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProfissionalCreaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelarAtualizacaoProfissional;
    private javax.swing.JButton btEditarProfissional;
    private javax.swing.JButton btExcluirProfissional;
    private javax.swing.JButton btFinalizarCadastroProfissional;
    private javax.swing.JComboBox<String> cbProfissionalEstado;
    private javax.swing.JCheckBox ckbProfissionalCpf;
    private javax.swing.JCheckBox ckbProfissionalNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnCadastrarNovoProfissional;
    private javax.swing.JPanel pnGerenciarProfissionais;
    private javax.swing.JTable tbProfissionaisCadastrados;
    private javax.swing.JTextField tfPalavraChaveProfissional;
    private javax.swing.JTextField tfProfissionalBairro;
    private javax.swing.JFormattedTextField tfProfissionalCelular;
    private javax.swing.JFormattedTextField tfProfissionalCep;
    private javax.swing.JTextField tfProfissionalCidade;
    private javax.swing.JFormattedTextField tfProfissionalCpf;
    private javax.swing.JFormattedTextField tfProfissionalCrea;
    private javax.swing.JFormattedTextField tfProfissionalCtma;
    private javax.swing.JTextField tfProfissionalNome;
    private javax.swing.JTextField tfProfissionalNumero;
    private javax.swing.JTextField tfProfissionalProfissao;
    private javax.swing.JTextField tfProfissionalRCC;
    private javax.swing.JTextField tfProfissionalRua;
    private javax.swing.JFormattedTextField tfProfissionalTelefone;
    private javax.swing.JTabbedPane tpnAbasProfissionais;
    // End of variables declaration//GEN-END:variables
}
