/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import bancodedados.ClienteBD;
import java.awt.Toolkit;
import java.util.ArrayList;
import modelo.tabelas.ModeloTabelaClientes;
import modelos.Cliente;

/**
 *
 * @author Jean
 */
public class TelaRelatorioCliente extends javax.swing.JDialog {

    ModeloTabelaClientes modeloTabelaCliente = new ModeloTabelaClientes();
    ClienteBD conexaoTabelaCliente = new ClienteBD();
    ArrayList<Cliente> listaOriginalTemporariaCliente = new ArrayList();
    Cliente clienteSelecionado = new Cliente();
    int categoria = 0;

    /**
     * Creates new form TelaRelatorioRecibo
     */
    public TelaRelatorioCliente(java.awt.Frame parent, boolean modal, int categoria_id) {
        super(parent, modal);
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/icon.png")));
        this.categoria = categoria_id;

        this.setLocationRelativeTo(parent);
        this.setTitle("Gerencia de clientes");
        tfBuscarCliente.requestFocus();
        tbListaClientes.setModel(modeloTabelaCliente);
        tbListaClientes.getTableHeader().setReorderingAllowed(false);

        if (this.categoria == 4) {
            buscarClientes();
        } else {
            buscarClientesNaTabela(categoria_id);
        }

        System.out.println(this.categoria);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfBuscarCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListaClientes = new javax.swing.JTable();
        btCancelarSelecaoCliente = new javax.swing.JButton();
        btSelecionarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisar Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setText("Nome do Cliente:");

        tfBuscarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfBuscarClienteKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfBuscarCliente)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tbListaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbListaClientes);

        btCancelarSelecaoCliente.setText("Cancelar");
        btCancelarSelecaoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarSelecaoClienteActionPerformed(evt);
            }
        });

        btSelecionarCliente.setText("Selecionar");
        btSelecionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelecionarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btCancelarSelecaoCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btSelecionarCliente))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelarSelecaoCliente)
                    .addComponent(btSelecionarCliente))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfBuscarClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscarClienteKeyReleased
        if (this.categoria == 4) {
            if (tfBuscarCliente.getText().isEmpty()) {
                modeloTabelaCliente.inserirListaClientes(conexaoTabelaCliente.selecionarTodosClientes());
            } else {
                modeloTabelaCliente.inserirListaClientes(conexaoTabelaCliente.selecionarTodosClientes());
                listaOriginalTemporariaCliente.clear();

                for (int i = 0; i < modeloTabelaCliente.retornaListaClientes().size(); i++) {
                    if (modeloTabelaCliente.retornaListaClientes().get(i).getCliente_nome().toLowerCase().contains(tfBuscarCliente.getText().toLowerCase())) {
                        listaOriginalTemporariaCliente.add(modeloTabelaCliente.retornaListaClientes().get(i));
                    }
                }

                modeloTabelaCliente.inserirListaClientes(listaOriginalTemporariaCliente);

            }

            tbListaClientes.updateUI();

        } else {
            if (tfBuscarCliente.getText().isEmpty()) {
                modeloTabelaCliente.inserirListaClientes(conexaoTabelaCliente.selecionarClientesCategoria(this.categoria));
            } else {
                modeloTabelaCliente.inserirListaClientes(conexaoTabelaCliente.selecionarClientesCategoria(this.categoria));
                listaOriginalTemporariaCliente.clear();

                for (int i = 0; i < modeloTabelaCliente.retornaListaClientes().size(); i++) {
                    if (modeloTabelaCliente.retornaListaClientes().get(i).getCliente_nome().toLowerCase().contains(tfBuscarCliente.getText().toLowerCase())) {
                        listaOriginalTemporariaCliente.add(modeloTabelaCliente.retornaListaClientes().get(i));
                    }
                }

                modeloTabelaCliente.inserirListaClientes(listaOriginalTemporariaCliente);

            }

            tbListaClientes.updateUI();

        }

    }//GEN-LAST:event_tfBuscarClienteKeyReleased

    private void btCancelarSelecaoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarSelecaoClienteActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btCancelarSelecaoClienteActionPerformed

    private void btSelecionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelecionarClienteActionPerformed
        // TODO add your handling code here:
        if (tbListaClientes.getSelectedRow() != -1) {
            clienteSelecionado = modeloTabelaCliente.retornaListaClientes().get(tbListaClientes.getSelectedRow());
        }

        this.setVisible(false);
        /*   if(tbCursosCadastrados.getSelectedRow()!=-1)
        {
            cursoSelecionado = modeloTabelaCursos.retornaListaCursos().get(tbCursosCadastrados.getSelectedRow());
        }
    }//GEN-LAST:event_btSelecionarClienteActionPerformed

    private void btSelecionarActionPerformed(java.awt.event.ActionEvent evt) {

        if (tbListaClientes.getSelectedRow() != -1) {
            clienteSelecionado = modeloTabelaCliente.retornaListaClientes().get(tbListaClientes.getSelectedRow());
        }

        this.setVisible(false);
        /*   if(tbCursosCadastrados.getSelectedRow()!=-1)
        {
            cursoSelecionado = modeloTabelaCursos.retornaListaCursos().get(tbCursosCadastrados.getSelectedRow());
        }
        
        this.setVisible(false);*/
// TODO add your handling code here:
    }

    public void buscarClientesNaTabela(int cate) {

        modeloTabelaCliente.inserirListaClientes(conexaoTabelaCliente.selecionarClientesCategoria(cate));
        listaOriginalTemporariaCliente = modeloTabelaCliente.retornaListaClientes();
        tbListaClientes.updateUI();

    }

    public void buscarClientes() {

        modeloTabelaCliente.inserirListaClientes(conexaoTabelaCliente.selecionarTodosClientes());
        listaOriginalTemporariaCliente = modeloTabelaCliente.retornaListaClientes();
        tbListaClientes.updateUI();

    }

    public Cliente retornarClienteSelecionado() {
        return clienteSelecionado;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaRelatorioCliente dialog = new TelaRelatorioCliente(new javax.swing.JFrame(), true, 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelarSelecaoCliente;
    private javax.swing.JButton btSelecionarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbListaClientes;
    private javax.swing.JTextField tfBuscarCliente;
    // End of variables declaration//GEN-END:variables
}
