/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import bancodedados.ClienteBD;
import bancodedados.ContratanteBD;
import java.util.ArrayList;
import modelo.tabelas.ModeloTabelaClientes;
import modelo.tabelas.ModeloTabelaContratantes;
import modelos.Cliente;
import modelos.Contratante;

/**
 *
 * @author Jean
 */
public class TelaRelatorioContrante extends javax.swing.JDialog {

    ModeloTabelaContratantes modeloTabelaContratante = new ModeloTabelaContratantes();
    ContratanteBD conexaoTabelaContratante = new ContratanteBD();
    ArrayList<Contratante> listaOriginalTemporariaContratante = new ArrayList();
    Contratante contratanteSelecionado = new Contratante();

    /**
     * Creates new form TelaRelatorioRecibo
     */
    public TelaRelatorioContrante(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setLocationRelativeTo(parent);
        this.setTitle("Gerencia de Contratantes");
        tfBuscarContratante.requestFocus();
        tbListaContratantes.setModel(modeloTabelaContratante);
        tbListaContratantes.getTableHeader().setReorderingAllowed(false);

        buscarContratantesNaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfBuscarContratante = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListaContratantes = new javax.swing.JTable();
        btCancelarSelecaoCliente = new javax.swing.JButton();
        btSelecionarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisar Contratante", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setText("Nome do Contratante:");

        tfBuscarContratante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfBuscarContratanteKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfBuscarContratante)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfBuscarContratante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tbListaContratantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbListaContratantes);

        btCancelarSelecaoCliente.setText("Cancelar");
        btCancelarSelecaoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarSelecaoClienteActionPerformed(evt);
            }
        });

        btSelecionarCliente.setText("Selecionar");
        btSelecionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelecionarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btCancelarSelecaoCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btSelecionarCliente))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelarSelecaoCliente)
                    .addComponent(btSelecionarCliente))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfBuscarContratanteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscarContratanteKeyReleased
        if (tfBuscarContratante.getText().isEmpty()) {
            modeloTabelaContratante.inserirListaContratantes(conexaoTabelaContratante.selecionarTodosContratantes());
        } else {
            modeloTabelaContratante.inserirListaContratantes(conexaoTabelaContratante.selecionarTodosContratantes());
            listaOriginalTemporariaContratante.clear();

            for (int i = 0; i < modeloTabelaContratante.retornarListaContratantes().size(); i++) {
                if (modeloTabelaContratante.retornarListaContratantes().get(i).getContratante_empresa().toLowerCase().contains(tfBuscarContratante.getText().toLowerCase())) {
                    listaOriginalTemporariaContratante.add(modeloTabelaContratante.retornarListaContratantes().get(i));
                }
            }

            modeloTabelaContratante.inserirListaContratantes(listaOriginalTemporariaContratante);

        }

        tbListaContratantes.updateUI();
    }//GEN-LAST:event_tfBuscarContratanteKeyReleased

    private void btCancelarSelecaoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarSelecaoClienteActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btCancelarSelecaoClienteActionPerformed

    private void btSelecionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelecionarClienteActionPerformed
        // TODO add your handling code here:
        if (tbListaContratantes.getSelectedRow() != -1) {
            contratanteSelecionado = modeloTabelaContratante.retornarListaContratantes().get(tbListaContratantes.getSelectedRow());
        }

        this.setVisible(false);
        /*   if(tbCursosCadastrados.getSelectedRow()!=-1)
        {
            cursoSelecionado = modeloTabelaCursos.retornaListaCursos().get(tbCursosCadastrados.getSelectedRow());
        }
    }//GEN-LAST:event_btSelecionarClienteActionPerformed

    private void btSelecionarActionPerformed(java.awt.event.ActionEvent evt) {

        if (tbListaClientes.getSelectedRow() != -1) {
            clienteSelecionado = modeloTabelaCliente.retornaListaClientes().get(tbListaClientes.getSelectedRow());
        }

        this.setVisible(false);
        /*   if(tbCursosCadastrados.getSelectedRow()!=-1)
        {
            cursoSelecionado = modeloTabelaCursos.retornaListaCursos().get(tbCursosCadastrados.getSelectedRow());
        }
        
        this.setVisible(false);*/
// TODO add your handling code here:
    }

    public void buscarContratantesNaTabela() {

        modeloTabelaContratante.inserirListaContratantes(conexaoTabelaContratante.selecionarTodosContratantes());
        listaOriginalTemporariaContratante = modeloTabelaContratante.retornarListaContratantes();
        tbListaContratantes.updateUI();

    }

    public Contratante retornarContratanteSelecionado() {
        return contratanteSelecionado;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioContrante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioContrante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioContrante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioContrante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaRelatorioContrante dialog = new TelaRelatorioContrante(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelarSelecaoCliente;
    private javax.swing.JButton btSelecionarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbListaContratantes;
    private javax.swing.JTextField tfBuscarContratante;
    // End of variables declaration//GEN-END:variables
}
